apiVersion: v1
kind: ConfigMap
metadata:
  name: ottam-config
  namespace: ottam
data:
  cfg.yml: |
    pubSub:
      url: nats:4222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ottam-http-server
  namespace: ottam
  labels:
    app: ottam-http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ottam-http-server
  template:
    metadata:
      labels:
        app: ottam-http-server
    spec:
      containers:
        - name: ottam-http-server
          image: ghcr.io/kychandar/ottam:dev
          imagePullPolicy: Always
          env:
            - name: GODEBUG
              value: "gctrace=1"              
          args: ["./app", "server", "--config=./cfg.yml"]
          workingDir: /app
          volumeMounts:
            - name: config-volume
              mountPath: /app/cfg.yml
              subPath: cfg.yml
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "2"
              memory: "4Gi"            
      volumes:
        - name: config-volume
          configMap:
            name: ottam-config
---
apiVersion: v1
kind: Service
metadata:
  name: ottam-http-server-headless
  namespace: ottam
spec:
  clusterIP: None
  selector:
    app: ottam-http-server
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ottam-http-server
  namespace: ottam
spec:
  type: NodePort
  selector:
    app: ottam-http-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080